from pathlib import Path
import markdown
ROOT = Path(__file__).resolve().parent
OUT = ROOT / "site"
OUT.mkdir(exist_ok=True)
css = (ROOT / "style.css").read_text(encoding="utf-8")
css += ".download{display:block;background:#294e40;color:#fff;text-decoration:none;padding:18px 22px;border-radius:10px;font-weight:700;margin:18px 0}.download:hover{background:#41674f}.download span{display:block;font-size:13px;font-weight:400;opacity:.85}"
def shell(title, body, lesson=False):
    return f'''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="phone_blocky 電控入門：從手機連線到積木控制，一步一步學會。"><title>{title} · ROBOT LAB</title><style>{css}</style></head><body><a class="skip" href="#main">跳至內容</a><header><a class="brand" href="index.html"><span class="brand-icon">R</span> ROBOT LAB <small>實作教室</small></a><nav aria-label="主要導覽"><a href="index.html#courses">課程地圖</a><a href="connect.html">開始學習 ↗</a></nav></header>{body}<footer><span>ROBOT LAB / phone_blocky</span><span>教學網站試作 · 教材整理於 2026.09.16</span></footer></body></html>'''
home = '''<main id="main"><section class="hero"><div><p class="eyebrow">PHONE_BLOCKY / 從零開始的電控實驗</p><h1>讓第一顆馬達，<br><em>照你的意思轉。</em></h1><p class="lead">一塊 ESP32、一支手機。從接線、連線到拖拉積木，<br class="desktop">把看不見的電控，變成看得見的動作。</p><a class="button" href="install.html">先下載燒錄工具 <span>↓</span></a><p class="caption">適合電控初學者 · 手機也能閱讀 · 依專案教材編寫</p></div><div class="diagram" role="img" aria-label="手機經 Wi-Fi 連到 ESP32 控制板，再控制馬達"><div class="diagram-top">YOUR FIRST CONNECTION <span>●</span></div><div class="phone">▥<small>你的手機</small></div><div class="signal">))) <span>Wi-Fi</span></div><div class="board"><span>ESP32</span><div class="chip">phone<br>blocky</div><small>CONTROL BOARD</small></div><div class="wire"></div><div class="motor">M<small>馬達與機構</small></div><div class="diagram-foot">01 燒錄它　→　02 連上它　→　03 指揮它</div></div></section><section class="intro"><p class="eyebrow">LEARN BY DOING</p><h2>每一步，都有看得見的成功訊號。</h2><p>不只告訴你按哪個按鈕，也告訴你應該看到什麼。卡住了，就沿著檢查步驟找原因。</p></section><section id="courses"><div class="section-title"><h2>你的學習路線</h2><span>先燒錄，再連上，最後讓它動起來</span></div><div class="cards"><a class="card active" href="install.html"><span class="badge">現在開始</span><div class="season">S0 / 上車</div><h3>下載並燒錄工具 <span>↓</span></h3><p>取得 Windows 整合工具，把韌體與手機網頁一次燒進控制板。</p><small>約 10 分鐘 · Windows 電腦</small></a><a class="card active" href="connect.html"><span class="badge">示範課已開放</span><div class="season">S0 / 上車</div><h3>手機連上它 <span>↗</span></h3><p>找到熱點、保持連線、打開主選單。先完成你的第一次連接。</p><small>約 5 分鐘 · 4 個操作步驟</small></a><article class="card"><span class="badge muted">課程規劃</span><div class="season">S1 / 動</div><h3>讓馬達開始轉</h3><p>認識 PWM 與方向，用第一支積木程式安排動作。</p><small>接續主題 · 尚未開放</small></article><article class="card"><span class="badge muted">課程規劃</span><div class="season">S2–S5 / 準、穩、判、交</div><h3>讓機構學會控制</h3><p>從編碼器與位置回授，走到感測、判斷與參數移交。</p><small>接續主題 · 尚未開放</small></article></div></section><aside class="note"><strong>這裡是教學教室，操作介面在板子上。</strong><p>閱讀教材需要存取本網站；控制 ESP32 時，請依課程連上板子的 Wi-Fi。切換前可將課程列印成 PDF 留存。</p></aside></main>'''
home = home.replace('<article class="card"><span class="badge muted">課程規劃</span><div class="season">S1 / 動</div><h3>讓馬達開始轉</h3><p>認識 PWM 與方向，用第一支積木程式安排動作。</p><small>接續主題 · 尚未開放</small></article>', '<a class="card active" href="motor.html"><span class="badge">S1 已開放</span><div class="season">S1 / 動</div><h3>讓馬達開始轉 <span>↗</span></h3><p>認識 PWM 與方向，用第一支積木程式安排動作。</p><small>約 15 分鐘 · 第一支積木程式</small></a>')
content = markdown.markdown((ROOT / "content/connect.md").read_text(encoding="utf-8"), extensions=["tables", "fenced_code"])
install_content = markdown.markdown((ROOT / "content/install.md").read_text(encoding="utf-8"), extensions=["tables", "fenced_code"])
motor_content = markdown.markdown((ROOT / "content/motor.md").read_text(encoding="utf-8"), extensions=["tables", "fenced_code"])
install = '''<main id="main" class="lesson"><a class="back" href="index.html#courses">← 回到課程地圖</a><div class="lesson-head"><p class="eyebrow">S0 上車篇 / E02</p><h1>燒錄：一輩子只做一次</h1><p class="lead">下載一個工具，完成控制板的韌體與手機網頁準備。</p><div class="lesson-meta"><span>約 10 分鐘</span><span>需要 Windows 電腦</span><button onclick="window.print()">列印／存成 PDF ↓</button></div></div><div class="lesson-grid"><aside class="lesson-side"><strong>本課任務</strong><p>01 下載工具</p><p>02 接上控制板</p><p>03 完成燒錄</p><p>04 重新啟動</p><hr><small>工具檔已內含韌體與 LittleFS 網頁。</small></aside><article>''' + install_content + '''<a class="button" href="connect.html">下一課：手機連上它 ↗</a></article></div></main>'''
motor = '''<main id="main" class="lesson"><a class="back" href="index.html#courses">← 回到課程地圖</a><div class="lesson-head"><p class="eyebrow">S1 動 / E10–E13</p><h1>讓馬達開始轉</h1><p class="lead">從第一個 PWM 指令，理解出力、方向與馬達個體差異。</p><div class="lesson-meta"><span>約 15 分鐘</span><span>需要已完成的控制板</span><button onclick="window.print()">列印／存成 PDF ↓</button></div></div><div class="lesson-grid"><aside class="lesson-side"><strong>本課任務</strong><p>01 組出動作</p><p>02 比較 PWM</p><p>03 驗證方向</p><p>04 觀察差異</p><hr><small>先從 30% 與一顆馬達開始。</small></aside><article>''' + motor_content + '''<a class="button" href="index.html#courses">返回學習路線 ↗</a></article></div></main>'''
lesson = '''<main id="main" class="lesson"><a class="back" href="index.html#courses">← 回到課程地圖</a><div class="lesson-head"><p class="eyebrow">S0 上車篇 / E04</p><h1>手機連上它</h1><p class="lead">把手機與控制板連在一起，打開你的電控實驗入口。</p><div class="lesson-meta"><span>約 5 分鐘</span><span>難度：入門</span><button onclick="window.print()">列印／存成 PDF ↓</button></div></div><div class="lesson-grid"><aside class="lesson-side"><strong>本課任務</strong><p>01 保留教學</p><p>02 連上 Wi-Fi</p><p>03 保持連線</p><p>04 打開主選單</p><hr><small>首次操作請先確認燒錄與接線已完成。</small></aside><article>''' + content + '''<section class="checklist"><h2>完成了嗎？</h2><p>三項都完成，就可以準備下一堂自檢課。</p><label><input type="checkbox"> 找到並連上自己的板子熱點</label><label><input type="checkbox"> 看得到板子的主選單</label><label><input type="checkbox"> 能打開「接線說明」頁面</label><small>勾選僅供本次閱讀使用，重新整理後會重設。</small></section><p class="source">教材來源：phone_blocky/docs/course/scripts/S0-E04-手機連上它.md、docs/卡住了怎麼辦.md、README.md。依本機文件整理；本頁未宣稱硬體已完成實測。</p><a class="button" href="index.html#courses">返回學習路線 ↗</a></article></div></main>'''
(OUT / "index.html").write_text(shell("從手機開始，學會電控", home), encoding="utf-8")
(OUT / "connect.html").write_text(shell("手機連上它", lesson, True), encoding="utf-8")
(OUT / "install.html").write_text(shell("下載並燒錄工具", install, True), encoding="utf-8")
(OUT / "motor.html").write_text(shell("讓馬達開始轉", motor, True), encoding="utf-8")
(OUT / ".nojekyll").write_text("", encoding="utf-8")
print("Built: " + str(OUT))
